### PR TITLE
[BUGFIX] Fix registration of FilePermissionsAspect slot

### LINKED ISSUE #150: Selection in folder tree is ignored
Since media 4.2.0 all files of a filestore are displayed regardless of the selected folder in the folder tree.

### PR DESCRIPTION
**Pull request by mbrodala**
This fixes a regression introduced with 9132e8e9e06b2cf6186b770b9a12af0cad03e6af.

Fixes #150

### CODE REVIEW

**Comment by mbrodala** [comment]
Notice that this change itself actually only brings the code in line with the remaining code but sheds light on the related breaking issue.

**Comment by mbrodala** [comment]
@fabarea Maybe you can merge this for consistency. :-)

**Comment by fabarea** [comment]
I don't think I can do that as the class `Fab\Vidi\Controller\Backend\ContentController::class` does not exist. It was moved quite some time ago to Fab\Vidi\Controller\ContentController::class to avoid some mapping in `Migrations/`. Now that the signal / slot was used with "Fab\Vidi\Controller\Backend\ContentController" I fear we have to stick to that for not breaking compatibility.

**Comment by mbrodala** [comment]
Have you tried? ;-) PHP doesn't care if whatever comes before `::class` really exists, you can use `Non\Existinging\Stuff\Like\This::class` and still get the proper FQCN string. There is not even autoloading, thus I'd still suggest to bring this in line.

**Comment by fabarea** [comment]
Ah, weird behaviour from PHP... I honestly don't particularly like cheating here as the IDE will mark it as error and I would prefer to use the Foo::class when the class really exists.

image

**Comment by mbrodala** [comment]
OK, I see your point. If desired you can maybe go the other way then and use strings for all of the signal class names but that's up to you. ;-)

**Comment by fabarea** [comment]
Let see, I quite like to use the class name as identifier for a signal / slot ; we are sure of the existence of the class and it is consistent as you said. It is just silly that in this particular case, I had to move the class around for better compatibility (got too many auto-load failures with 7.x migration). What I was thinking is to deprecate the old signal name and introduce the correct one. The old would log a message into the deprecated log and could be removed in one major version of TYPO3. That way I would feel it really consistent... But still hesitant as it does not bring a lot of value.

**Comment by mbrodala** [comment]
Sure thing, don't worry about this too much. Maybe add a comment above that line to make sure everyone reading that section understands the exception.

**Pull request closed without merging**
